r2013-02-18-tunr/config/routes.rb
R20130218Tunr::Application.routes.draw do
  root :to => 'home#index'
  resources :artists, :genres, :mixtapes

  resources :albums do
    member do
      post 'buy'
    end
  end


  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end

  resources :songs do
    member do
      post 'buy'
      get 'purchase'
    end
  end

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

r2013-02-18-tunr/app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :text
#  filename   :string(255)
#  artist_id  :integer
#  album_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  price      :decimal(, )      default(0.0)
#

class Song < ActiveRecord::Base
  attr_accessible :name, :image, :filename, :album_id, :artist_id, :genre_ids, :price, :mixtape_ids
  belongs_to :album
  belongs_to :artist
  has_and_belongs_to_many :mixtapes
  has_and_belongs_to_many :genres
  validates :name, :presence => true
  validates :filename, :presence => true


end

r2013-02-18-tunr/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  image           :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  is_admin        :boolean          default(FALSE)
#  balance         :decimal(, )      default(0.0)
#

class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :name, :image, :password, :password_confirmation, :balance
  has_many :mixtapes
  has_and_belongs_to_many :albums
  validates :image, :presence => true
  validates :name, :uniqueness => true, :length => { :minimum => 3 }
  validates :balance, :numericality => { :greater_than_or_equal_to => 0 }

end

r2013-02-18-tunr/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :check_if_admin, :except => [:index, :show, :purchase, :buy]

  def index
    @songs = Song.order(:name)
  end

  def new
    @song = Song.new
  end

  def create
    @songs = Song.new(params[:song])
    if @songs.save
      redirect_to(songs_path)
    else
      render :new
    end
  end

  def edit
    @song = Song.find(params[:id])
    render :new
  end

  def update
    @song = Song.find(params[:id])
    if @song.update_attributes(params[:song])
      redirect_to(songs_path)
    else
      render :new
    end
  end

  def purchase
    @song = Song.find(params[:id])
  end

  def buy
    @song = Song.find(params[:id])
    if @song.update_attributes(params[:user])
      @auth.balance -= @song.price
      @auth.save
      # params[:song][:mixtape_ids].each do |mix_id|
      #   mixtape = Mixtape.find(mix_id)
      #   mixtape.songs << @song
      # end
      redirect_to(mixtape_path)
    else
      redirect_to(@song.album)
    end
  end

  def destroy
  end

  def show
    @song = Song.find(params[:id])
  end

end

r2013-02-18-tunr/app/views/songs/index.html.haml
%table
  - @songs.each do |song|
    %tr{:class => cycle('row0', 'row1')}
      %td= link_to(song.name, song_path(song))

      - if @auth && @auth.balance.to_d > song.price.to_d && !is_admin
        %td= button_to('BUY ' + number_to_currency(song.price), purchase_song_path(song), :method => :get, :class => 'button radius tiny')
      - else
        %td= button_to('BUY ' + number_to_currency(song.price), purchase_song_path(song), :method => :get, :disabled => true, :class => 'button radius tiny')

      %td= link_to('Edit', edit_song_path(song), :class => 'button radius tiny') if is_admin

%p.newlink= link_to('New Song', new_song_path, :class => 'button radius tiny') if is_admin

r2013-02-18-tunr/app/views/songs/new.html.haml
.row
  .four.columns
    = render(:partial => 'shared/errors', :locals => {:object => @song})
    = form_for @song do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true;
      = f.label :filename
      = f.text_field :filename
      = f.label :image
      = f.text_field :image
      = f.label :price
      = f.text_field :price

      - Genre.order(:name).each do |genre|
        = genre.name
        = check_box_tag 'song[genre_ids][]', genre.id, genre.in?(@song.genres.to_a)

      = f.submit nil, :class => 'button radius'
  .eight.columns

r2013-02-18-tunr/app/views/songs/purchase.html.haml
%h3= @song.name

- if !@song.artist.nil?
  %h5= "Performed by " + @song.artist.name

%h1 AT LEAST THIS IS WORKING!


= form_tag buy_song_path(@song) do
  - @auth.mixtapes.each do |mixtape|
    = mixtape.name
    = check_box_tag 'user[mixtape_ids][]', mixtape.id, mixtape.in?(@song.mixtapes.to_a)

  = submit_tag



/ = form_tag buy_song_path(@song) do
/   .row
/     %fieldset
/       %legend Add to a Mixtape!
/       - if @auth.mixtapes.count == 1
/         %p You have no mixtapes! Get it together!
/       - else
/         - @auth.mixtapes.each do |mixtape|
/           - if mixtape.name != 'Library'
/             %p{ :class => 'left skill_checkboxes' }
/               = mixtape.name
/               = check_box_tag 'user[mixtape_ids][]', mixtape.id
/   = submit_tag

r2013-02-18-tunr/app/views/songs/show.html.erb
<h2><%= @song.name %></h2>

<% if !@song.album.nil? %>
  <h5>From the album <%= @song.album.name %></h5>
<% end %>

<% if @auth && @auth.balance.to_d > @song.price.to_d && !is_admin %>
  <%= button_to('BUY ' + number_to_currency(@song.price), purchase_song_path(@song), :method => :get) %>
<% else %>
  <%= button_to('BUY ' + number_to_currency(@song.price), purchase_song_path(@song), :method => :get, :disabled => true) %>
<% end %>




<p><%= audio_tag(@song.filename, :controls => true) %></p>
<table>
  <% @song.genres.each do |genre| %>
  <tr>
    <td><%= genre.name %></td>
  </tr>
  <% end %>
</table>